# Site settings
title: Vaishali Rajurkar
email: post.vaishalirajurkar@gmail.com
description: "My name is anthony  gonsalves "
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vaishalirajurkar.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Permalinks
permalink: none

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  work:
    output: true

# Plugin
plugins:
- jekyll-autoprefixer

# all projects
allprojects:
- byd
- evbox
- jde  
